### ISSUE TITLE
Separate Twitter input credentials

### ISSUE THREAD

**Issue by jamesmawm** [jamesmawm/twitter-stream#7]
Separate Twitter input credentials from the config file (dashboard.js).
Preferably load dashboard.js Twitter variables from either a separate text file or user keyboard input from the console.

**Comment by darrylpargeter** [comment]
Hey @jamesmawm 

Is this one free? and possible for me to work on?

**Comment by kieranajp** [comment]
@darrylpargeter Ah sorry, I literally just did this one :) feel free to CR.
